//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAUI_LAB.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class AppResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal AppResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MAUI_LAB.Properties.AppResource", typeof(AppResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Version.
        /// </summary>
        public static string Account_App_Version {
            get {
                return ResourceManager.GetString("Account_App_Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Password.
        /// </summary>
        public static string Account_Change_Password {
            get {
                return ResourceManager.GetString("Account_Change_Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to log out ?.
        /// </summary>
        public static string Account_Confirm_Logout_Msg {
            get {
                return ResourceManager.GetString("Account_Confirm_Logout_Msg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm log out.
        /// </summary>
        public static string Account_Confirm_Logout_Title {
            get {
                return ResourceManager.GetString("Account_Confirm_Logout_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Account_Logout {
            get {
                return ResourceManager.GetString("Account_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rate App.
        /// </summary>
        public static string Account_Rate_App {
            get {
                return ResourceManager.GetString("Account_Rate_App", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to App Setting.
        /// </summary>
        public static string Account_Setting {
            get {
                return ResourceManager.GetString("Account_Setting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Info.
        /// </summary>
        public static string Account_Staff_Info {
            get {
                return ResourceManager.GetString("Account_Staff_Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Confirm_Cancel {
            get {
                return ResourceManager.GetString("Confirm_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Confirm_Logout {
            get {
                return ResourceManager.GetString("Confirm_Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ok.
        /// </summary>
        public static string Confirm_Ok {
            get {
                return ResourceManager.GetString("Confirm_Ok", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Gender_Female {
            get {
                return ResourceManager.GetString("Gender_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Gender_Male {
            get {
                return ResourceManager.GetString("Gender_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Other.
        /// </summary>
        public static string Gender_Other {
            get {
                return ResourceManager.GetString("Gender_Other", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address.
        /// </summary>
        public static string Label_Address {
            get {
                return ResourceManager.GetString("Label_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Label_Cancel {
            get {
                return ResourceManager.GetString("Label_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Label_Close {
            get {
                return ResourceManager.GetString("Label_Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Label_Delete {
            get {
                return ResourceManager.GetString("Label_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Label_Edit {
            get {
                return ResourceManager.GetString("Label_Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Label_Email {
            get {
                return ResourceManager.GetString("Label_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Label_Gender {
            get {
                return ResourceManager.GetString("Label_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        public static string Label_PhoneNumber {
            get {
                return ResourceManager.GetString("Label_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Position.
        /// </summary>
        public static string Label_Position {
            get {
                return ResourceManager.GetString("Label_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Label_Save {
            get {
                return ResourceManager.GetString("Label_Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new staff.
        /// </summary>
        public static string Label_Staff_Add {
            get {
                return ResourceManager.GetString("Label_Staff_Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete staff.
        /// </summary>
        public static string Label_Staff_Delete {
            get {
                return ResourceManager.GetString("Label_Staff_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff List.
        /// </summary>
        public static string Label_Staff_List {
            get {
                return ResourceManager.GetString("Label_Staff_List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update staff info.
        /// </summary>
        public static string Label_Staff_Update {
            get {
                return ResourceManager.GetString("Label_Staff_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View staff detail.
        /// </summary>
        public static string Label_Staff_View {
            get {
                return ResourceManager.GetString("Label_Staff_View", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff name.
        /// </summary>
        public static string Label_StaffName {
            get {
                return ResourceManager.GetString("Label_StaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to English - US.
        /// </summary>
        public static string Language_En_US {
            get {
                return ResourceManager.GetString("Language_En_US", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tiếng Việt.
        /// </summary>
        public static string Language_Vi_VN {
            get {
                return ResourceManager.GetString("Language_Vi_VN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Language.
        /// </summary>
        public static string Main_Page_LabelSelectLanguage {
            get {
                return ResourceManager.GetString("Main_Page_LabelSelectLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Main_Page_PlaceHolderPassword {
            get {
                return ResourceManager.GetString("Main_Page_PlaceHolderPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string Main_Page_PlaceHolderUserName {
            get {
                return ResourceManager.GetString("Main_Page_PlaceHolderUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password ?.
        /// </summary>
        public static string Main_Page_TextForgotPassword {
            get {
                return ResourceManager.GetString("Main_Page_TextForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Main_Page_TextLogin {
            get {
                return ResourceManager.GetString("Main_Page_TextLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        public static string Main_Page_TextRememberPassword {
            get {
                return ResourceManager.GetString("Main_Page_TextRememberPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Version.
        /// </summary>
        public static string Main_Page_TextVersion {
            get {
                return ResourceManager.GetString("Main_Page_TextVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        public static string Main_Tabbed_Page_Account {
            get {
                return ResourceManager.GetString("Main_Tabbed_Page_Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Notification.
        /// </summary>
        public static string Main_Tabbed_Page_Bell {
            get {
                return ResourceManager.GetString("Main_Tabbed_Page_Bell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Main_Tabbed_Page_Home {
            get {
                return ResourceManager.GetString("Main_Tabbed_Page_Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Listing.
        /// </summary>
        public static string Main_Tabbed_Page_Listing {
            get {
                return ResourceManager.GetString("Main_Tabbed_Page_Listing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be emtpy.
        /// </summary>
        public static string MSG_ADDRESS_CANNOT_EMPTY {
            get {
                return ResourceManager.GetString("MSG_ADDRESS_CANNOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot contain some specical characters.
        /// </summary>
        public static string MSG_ADDRESS_CONTAIN_SPECIALCHARACTERS {
            get {
                return ResourceManager.GetString("MSG_ADDRESS_CONTAIN_SPECIALCHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure to delete driver {0} - {1} ?.
        /// </summary>
        public static string MSG_CONFIRM_DELETE {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_DELETE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Delete.
        /// </summary>
        public static string MSG_CONFIRM_DELETE_TITLE {
            get {
                return ResourceManager.GetString("MSG_CONFIRM_DELETE_TITLE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Network Connection.
        /// </summary>
        public static string MSG_DISCONNECTED {
            get {
                return ResourceManager.GetString("MSG_DISCONNECTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email cannot be empty.
        /// </summary>
        public static string MSG_EMAIL_NOT_EMPTY {
            get {
                return ResourceManager.GetString("MSG_EMAIL_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email not valid.
        /// </summary>
        public static string MSG_EMAIL_NOT_VALID {
            get {
                return ResourceManager.GetString("MSG_EMAIL_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password cannot be empty.
        /// </summary>
        public static string MSG_ENTER_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_ENTER_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User ID cannot be empty.
        /// </summary>
        public static string MSG_ENTER_USER_ID {
            get {
                return ResourceManager.GetString("MSG_ENTER_USER_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select valid gender.
        /// </summary>
        public static string MSG_GENDER_NOT_VALID {
            get {
                return ResourceManager.GetString("MSG_GENDER_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login Error.
        /// </summary>
        public static string MSG_LOGIN_ERROR {
            get {
                return ResourceManager.GetString("MSG_LOGIN_ERROR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number cannot contain some specical characters.
        /// </summary>
        public static string MSG_PHONE_NUMBER_CONTAIN_SPECIALCHARACTERS {
            get {
                return ResourceManager.GetString("MSG_PHONE_NUMBER_CONTAIN_SPECIALCHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number must not be emtpy.
        /// </summary>
        public static string MSG_PHONE_NUMBER_NOT_EMPTY {
            get {
                return ResourceManager.GetString("MSG_PHONE_NUMBER_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number not valid.
        /// </summary>
        public static string MSG_PHONE_NUMBER_NOT_VALID {
            get {
                return ResourceManager.GetString("MSG_PHONE_NUMBER_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number contain word, contain number only.
        /// </summary>
        public static string MSG_PHONE_NUMBER_NUMBER_ONLY {
            get {
                return ResourceManager.GetString("MSG_PHONE_NUMBER_NUMBER_ONLY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select valid Position.
        /// </summary>
        public static string MSG_POSITION_NOT_VALID {
            get {
                return ResourceManager.GetString("MSG_POSITION_NOT_VALID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff Deleted.
        /// </summary>
        public static string MSG_STAFF_DELETED {
            get {
                return ResourceManager.GetString("MSG_STAFF_DELETED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email Exist.
        /// </summary>
        public static string MSG_STAFF_DUPLICATE_EMAIL {
            get {
                return ResourceManager.GetString("MSG_STAFF_DUPLICATE_EMAIL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone Number Exist.
        /// </summary>
        public static string MSG_STAFF_PHONE_NUMBER {
            get {
                return ResourceManager.GetString("MSG_STAFF_PHONE_NUMBER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User exist, please choose other User ID.
        /// </summary>
        public static string MSG_USER_EXIST {
            get {
                return ResourceManager.GetString("MSG_USER_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account banned.
        /// </summary>
        public static string MSG_USER_LOGIN_BANNED {
            get {
                return ResourceManager.GetString("MSG_USER_LOGIN_BANNED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not exist user on the system.
        /// </summary>
        public static string MSG_USER_LOGIN_NOT_EXIST {
            get {
                return ResourceManager.GetString("MSG_USER_LOGIN_NOT_EXIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account temporary Suppended.
        /// </summary>
        public static string MSG_USER_LOGIN_SUPPENDED {
            get {
                return ResourceManager.GetString("MSG_USER_LOGIN_SUPPENDED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Wrong User ID or Password.
        /// </summary>
        public static string MSG_USER_LOGIN_WRONG_USERNAME_OR_PASSWORD {
            get {
                return ResourceManager.GetString("MSG_USER_LOGIN_WRONG_USERNAME_OR_PASSWORD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name cannot contain some specical characters.
        /// </summary>
        public static string MSG_USER_NAME_CONTAIN_SPECIALCHARACTERS {
            get {
                return ResourceManager.GetString("MSG_USER_NAME_CONTAIN_SPECIALCHARACTERS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name cannot be emtpy.
        /// </summary>
        public static string MSG_USER_NAME_NOT_EMPTY {
            get {
                return ResourceManager.GetString("MSG_USER_NAME_NOT_EMPTY", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name character is over 50.
        /// </summary>
        public static string MSG_USER_NAME_OVER_CHARACTER {
            get {
                return ResourceManager.GetString("MSG_USER_NAME_OVER_CHARACTER", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Gender.
        /// </summary>
        public static string Picker_Select_Gender {
            get {
                return ResourceManager.GetString("Picker_Select_Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Position.
        /// </summary>
        public static string Picker_Select_Position {
            get {
                return ResourceManager.GetString("Picker_Select_Position", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter address.
        /// </summary>
        public static string PlaceHolder_Address {
            get {
                return ResourceManager.GetString("PlaceHolder_Address", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Email.
        /// </summary>
        public static string PlaceHolder_Email {
            get {
                return ResourceManager.GetString("PlaceHolder_Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter phone number.
        /// </summary>
        public static string PlaceHolder_PhoneNumber {
            get {
                return ResourceManager.GetString("PlaceHolder_PhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search staff.
        /// </summary>
        public static string PlaceHolder_SearchBar {
            get {
                return ResourceManager.GetString("PlaceHolder_SearchBar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter staff name.
        /// </summary>
        public static string PlaceHolder_StaffName {
            get {
                return ResourceManager.GetString("PlaceHolder_StaffName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manager.
        /// </summary>
        public static string Position_GD {
            get {
                return ResourceManager.GetString("Position_GD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Staff.
        /// </summary>
        public static string Position_NV {
            get {
                return ResourceManager.GetString("Position_NV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chief of Department.
        /// </summary>
        public static string Position_TP {
            get {
                return ResourceManager.GetString("Position_TP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select Filter Options.
        /// </summary>
        public static string Select_Filter_Options {
            get {
                return ResourceManager.GetString("Select_Filter_Options", resourceCulture);
            }
        }
    }
}
